### ISSUE TITLE
Task: tweak `is_raster_data` logic to be less strict

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-stac#6]
As reported on Slack and in #5 some qa bands from [Landsat Collection](https://landsatlook.usgs.gov/stac-server/collections/landsat-c2l2-sr) are not returned by `odc.stac.load`. This is because `is_raster_data(..)` function returns False for `qa_*` bands from that collection.

```json
"cloud_qa": {
  "title": "Cloud Quality Analysis Band",
  "description": "Collection 2 Level-2 Cloud Quality Opacity Band Surface Reflectance",
  "type": "image/vnd.stac.geotiff; cloud-optimized=true",
  "roles": [
    "metadata",
    "cloud",
    "cloud-shadow",
    "snow-ice",
    "water-mask"
  ]
}
```

Example of band that is ignored by code linked below

https://github.com/opendatacube/odc-stac/blob/5d94d48c3d6418681d05667d004b704b5a55a7ba/odc/stac/_eo3.py#L136-L163

### Proposed fix

1. Only use  `asset.roles` as PASS filter only and do not reject, `"data" in asset.roles ==> ACCEPT`
2. Otherwise check for `"image/" in asset.media_type` and maybe detect and reject thumbnails?

I'm thinking this kind of logic

- If `roles` contain "data" assume raster band
- If media type has `"image/"` then assume Raster Band unless it is a thumbnail (is there a standard `role` for that?)
- If there is no data role and no media type, but asset has proj extension data then assume raster band
- Finally check if `href` looks like it's linking to tif file?

It's probably worthwhile adding config option that allows hard override for what assets to consider as raster bands.

cc: @gadomski

**Comment by gadomski** [comment]
> It's probably worthwhile adding config option that allows hard override for what assets to consider as raster bands.

Agree with this for sure, since there's no hard and fast rule, makes sense to provide the user a way to give us this information. Other than that, I'd say your heuristic makes sense to me -- media type in particular seems like a useful check.

> If roles contain "data" assume raster band

There have been ongoing discussions of how to support vector data w/ STAC (e.g. https://github.com/radiantearth/stac-spec/issues/1150), so `"data" in roles` might not be a hard-and-fast way of asserting that a given asset is a raster, anyways. One more argument for allowing the user to tell us which assets to use.
